version: '3.8'

services:
  app:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app  # Mount current directory to /app in container
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PYTHONUNBUFFERED=1  # Enable Python output buffering
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload  # Use uvicorn directly with reload 